#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME   "D10A_HighScreen"
#define BTA_DISABLE_DELAY 1000 /* in milliseconds */
#define BLUETOOTH_QCOM_SW TRUE
#define BLUETOOTH_QCOM_LE_INTL_SCAN TRUE
#define BTC_INCLUDED TRUE
#endif
